name: task_manager_clean
description: "A task manager app built with Firebase typically utilizes Firebase's Realtime Database for data storage, allowing users to create, update, and delete tasks in real-time. It often includes features like user authentication, task categorization, and notifications, providing a seamless experience across devices."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  provider: ^6.1.5
  intl: ^0.20.2
  flutter_slidable: ^4.0.0
  shared_preferences: ^2.5.3
  fl_chart: ^1.0.0
  table_calendar: ^3.2.0
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logoo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#FFFFFF" # only for Android 8.0+
  adaptive_icon_foreground: "assets/images/logoo.png" # only for Android 8.0+
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/