// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkiRV9H3XSeGM3KDF8mT8Z2vjp1Ps-FPI',
    appId: '1:866805703222:web:632827ec7401a0dc0dee97',
    messagingSenderId: '866805703222',
    projectId: 'postpolly-32d6f',
    authDomain: 'postpolly-32d6f.firebaseapp.com',
    storageBucket: 'postpolly-32d6f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJkWxs9b7_1q8jcmWOIOygMlJ2xBanSK0',
    appId: '1:866805703222:android:fd3fff63d65f7ece0dee97',
    messagingSenderId: '866805703222',
    projectId: 'postpolly-32d6f',
    storageBucket: 'postpolly-32d6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZd1DWWXyNJo1q6VzVkJcGbo7aAGBKBWI',
    appId: '1:866805703222:ios:ed3614604bc0e27b0dee97',
    messagingSenderId: '866805703222',
    projectId: 'postpolly-32d6f',
    storageBucket: 'postpolly-32d6f.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTaskManagerNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZd1DWWXyNJo1q6VzVkJcGbo7aAGBKBWI',
    appId: '1:866805703222:ios:ed3614604bc0e27b0dee97',
    messagingSenderId: '866805703222',
    projectId: 'postpolly-32d6f',
    storageBucket: 'postpolly-32d6f.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTaskManagerNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkiRV9H3XSeGM3KDF8mT8Z2vjp1Ps-FPI',
    appId: '1:866805703222:web:e39f024d6a88fdaa0dee97',
    messagingSenderId: '866805703222',
    projectId: 'postpolly-32d6f',
    authDomain: 'postpolly-32d6f.firebaseapp.com',
    storageBucket: 'postpolly-32d6f.firebasestorage.app',
  );

}